[package]
name = "chess_ai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.2.0"
clearscreen = "3.0.0"
colored = "2.1.0"
rayon = "1.10.0"
serde = "1.0.201"
text_io = "0.1.12"
